### ISSUE TITLE
Libressl works on ARM64?

### ISSUE THREAD

**Issue by bagajjal** [libressl-portable/portable#384] opened 2018-01-26 02:23 UTC
I couldn't get LibreSSL ARM64 binaries work on Windows OS.
Does LibreSSL ARM64 binaries work in other OS flavors (unix / Linux, etc)?
Is there any code that is the specific to ARM64 that might cause this?

I am using LibreSSL from openSSH.
When I try to generate keys (ssh-keygen.exe -A) it gets into an infinite loop in BN_generate_prime_ex().
Also, If I try to use keys generated on my X86 machine, I get "Invalid format" error.

Unfortunately I couldn't debug further as I couldn't load LibreSSL binaries in debug mode.

Here is the call stack,

**call stack 1**
```
\# Child-SP          RetAddr           Call Site
00 000000cc`808fd410 00007ffb`b4b33c40 libcrypto!bn_mul_add_words+0x74
01 000000cc`808fd410 00007ffb`b4b33e90 libcrypto!BN_from_montgomery+0x150
02 000000cc`808fd470 00007ffb`b4b2d018 libcrypto!BN_mod_mul_montgomery+0x80
03 000000cc`808fd4c0 00007ffb`b4b372f0 libcrypto!BN_mod_exp_mont_consttime+0x418
04 000000cc`808fd580 00007ffb`b4b36ebc libcrypto!BN_is_prime_fasttest_ex+0x340
05 000000cc`808fd600 00007ffb`b4ba671c libcrypto!BN_generate_prime_ex+0x39c
06 000000cc`808fe690 00007ff7`573ad5c8 libcrypto!RSA_generate_key_ex+0x16c
07 (Inline Function) --------`-------- ssh_keygen!rsa_generate_private_key+0x78 [c:\ba\1\s\openssh-portable\sshkey.c @ 1404] 
08 000000cc`808fe750 00007ff7`573a4908 ssh_keygen!sshkey_generate+0x410 [c:\ba\1\s\openssh-portable\sshkey.c @ 1563] 
09 000000cc`808febc0 00007ff7`573a9074 ssh_keygen!do_gen_all_hostkeys+0x298 [c:\ba\1\s\openssh-portable\ssh-keygen.c @ 1052] 
0a 000000cc`808ff120 00007ff7`573a9ad4 ssh_keygen!main+0xa1c [c:\ba\1\s\openssh-portable\ssh-keygen.c @ 2781] 
0b 000000cc`808ff860 00007ff7`573e7984 ssh_keygen!wmain+0xac [c:\ba\1\s\openssh-portable\contrib\win32\win32compat\wmain_common.c @ 61] 
0c (Inline Function) --------`-------- ssh_keygen!invoke_main+0x24 [f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl @ 90] 
0d 000000cc`808ff890 00007ff7`573e7a00 ssh_keygen!__scrt_common_main_seh+0x124 [f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl @ 283] 
0e (Inline Function) --------`-------- ssh_keygen!__scrt_common_main+0x8 [f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl @ 325] 
0f 000000cc`808ff8d0 00007ffb`e0115b64 ssh_keygen!wmainCRTStartup+0x10 [f:\dd\vctools\crt\vcstartup\src\startup\exe_wmain.cpp @ 16] 
10 000000cc`808ff8e0 00007ffb`e2580d94 KERNEL32!BaseThreadInitThunk+0x34
11 000000cc`808ff920 00000000`00000000 ntdll!RtlUserThreadStart+0x44
```

**call stack 2**
```
\ # Child-SP          RetAddr           Call Site
00 000000cc`808fd600 00007ffb`b4b36c7c libcrypto!BN_mod_word+0x44
01 000000cc`808fd600 00007ffb`b4ba671c libcrypto!BN_generate_prime_ex+0x15c
02 000000cc`808fe690 00007ff7`573ad5c8 libcrypto!RSA_generate_key_ex+0x16c
03 (Inline Function) --------`-------- ssh_keygen!rsa_generate_private_key+0x78 [c:\ba\1\s\openssh-portable\sshkey.c @ 1404] 
04 000000cc`808fe750 00007ff7`573a4908 ssh_keygen!sshkey_generate+0x410 [c:\ba\1\s\openssh-portable\sshkey.c @ 1563] 
05 000000cc`808febc0 00007ff7`573a9074 ssh_keygen!do_gen_all_hostkeys+0x298 [c:\ba\1\s\openssh-portable\ssh-keygen.c @ 1052] 
06 000000cc`808ff120 00007ff7`573a9ad4 ssh_keygen!main+0xa1c [c:\ba\1\s\openssh-portable\ssh-keygen.c @ 2781] 
07 000000cc`808ff860 00007ff7`573e7984 ssh_keygen!wmain+0xac [c:\ba\1\s\openssh-portable\contrib\win32\win32compat\wmain_common.c @ 61] 
08 (Inline Function) --------`-------- ssh_keygen!invoke_main+0x24 [f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl @ 90] 
09 000000cc`808ff890 00007ff7`573e7a00 ssh_keygen!__scrt_common_main_seh+0x124 [f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl @ 283] 
0a (Inline Function) --------`-------- ssh_keygen!__scrt_common_main+0x8 [f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl @ 325] 
0b 000000cc`808ff8d0 00007ffb`e0115b64 ssh_keygen!wmainCRTStartup+0x10 [f:\dd\vctools\crt\vcstartup\src\startup\exe_wmain.cpp @ 16] 
0c 000000cc`808ff8e0 00007ffb`e2580d94 KERNEL32!BaseThreadInitThunk+0x34
0d 000000cc`808ff920 00000000`00000000 ntdll!RtlUserThreadStart+0x44
```

**Comment by bagajjal** [comment] 2018-01-29 19:40
@kinichiro - Could you please have a look at this issue.

**Comment by busterb** [comment] 2018-01-29 20:17
I’d bring this up on the openbsd-tech mailing list. Are you able to replicate it on an ARM64 target under OpenBSD?

**Comment by bagajjal** [comment] 2018-01-29 20:24
No, We don't have ARM64 OpenBSD environment.

**Comment by kinichiro** [comment] 2018-01-29 22:58
I have several questions.

- What OS and version do you want to do this ?
- What H/W are you using for this ?
- Where did you get OpenSSH from ?
- What LibreSSL version do you use for this ?
- Did you comile your OpenSSH and LibreSSL by yourself on your ARM64
environment ?

**Comment by bagajjal** [comment] 2018-01-29 23:16
@kinichiro  - Thanks for your response. Does LibreSSL work on other ARM64 OS environments like unix, OpenBSD, etc?

Please see my inline,

- What OS and version do you want to do this ?
Windows 10.

- What H/W are you using for this ?
I have build the ARM64 binaries using my [docker image](https://cloud.docker.com/swarm/balu1202/repository/docker/balu1202/winservercore_vs2017build_arm/general) that contains windows server core, visual studio 15.4.3.
For testing, I used ARM64 windows 10 machine (snapdragon 835 processor).

- Where did you get OpenSSH from ?
https://github.com/PowerShell/Win32-OpenSSH/releases. I am part of this team.

- What LibreSSL version do you use for this ?
I tried v2.6.2, v2.6.4. 

- Did you comile your OpenSSH and LibreSSL by yourself on your ARM64
environment ?
compiled on windows 10 AMD64 machine.

**Comment by kinichiro** [comment] 2018-01-30 14:20
Excuse me, but, I edited your first post a little bit to see call stack well.

I have no idea about LibreSSL on ARM64 arch, yet.
I don't have ARM64 environment, and I can't test it.

Did you run LibreSSL regression tests after compiling by Visual Studio 2015 on your ARM64 Windows 10 machine ?
And are they passed successfully ?

Can you try to run your own build openssl.exe to generate RSA key like this ?

```
C:\libressl> openssl.exe genrsa -out test.key 2048
................................................................................
................................................................................
................................................................................
.....................................................+++
............................+++
e is 65537 (0x10001)
```

I could generate RSA key on my Windows7(64bit) as above.

**Comment by bagajjal** [comment] 2018-02-03 01:00
@kinichiro - 
Thanks for pointing to openssl.exe.

It looks like visual studio compiler issue.

openssl.exe is able to generate the key file with Debug mode binaries. Release mode binaries are going in an infinite loop.

**Comment by 4a6f656c** [comment] 2018-02-08 02:16
The openbsd/arm64 port runs with LibreSSL/OpenSSH so I'm pretty sure that there are no significant issues with LibreSSL on ARM-64. Since this seems like a compiler problem, I'm going to close this issue. Please reopen if need be.

**Closed by 4a6f656c** 2018-02-08 02:16 UTC
Labels: question
