### ISSUE TITLE
github master, CMake configure error

### ISSUE THREAD

**Issue by Dravion** [libressl-portable/portable#466] opened 2018-11-16 11:36 UTC
I just checked out master and run into some new CMake errors which didnt exist in LibreSSL 2.8.2 tar.gz
I attached the CMake logs
[CMakeError.log](https://github.com/libressl-portable/portable/files/2589092/CMakeError.log)
[CMakeOutput.log](https://github.com/libressl-portable/portable/files/2589093/CMakeOutput.log)

**Comment by busterb** [comment] 2018-11-16 15:57
That appears to simply be cmake testing the system as part of the autoconfiguration process. These are expected outputs, since it builds test programs and sees if the build successfully or not to determine system capabilities. If you didn't see them on 2.8.2, then it is probably because the system caches results.

If there is something specific in the logs you posted, please point it out, but I didn't see anything out of the ordinary.

**Comment by busterb** [comment] 2018-11-16 16:00
Master here is also automatically regression-tested and emails the developers on failures, so you do not have to report those individually (e.g. I just synced the latest OpenBSD sources, and the regression system caught a failure in master currently: https://travis-ci.org/libressl-portable/portable/builds/455928430). That should be fixed upstream soon.

**Closed by busterb** 2018-11-16 16:00 UTC
