### ISSUE TITLE
Use uClibc  to build libressl will get error: uClibc on noMMU doesn't provide __register_atfork()

### ISSUE THREAD

**Issue by redbirdtek** [libressl-portable/portable#538] opened 2019-07-01 03:38 UTC
#ifdef __GLIBC__ 
extern void *__dso_handle; 
extern int __register_atfork(void (*)(void), void(*)(void), void (*)(void), void *); 
#define _ARC4_ATFORK(f) __register_atfork(NULL, NULL, (f), __dso_handle) 
#else 
#define _ARC4_ATFORK(f) pthread_atfork(NULL, NULL, (f)) 
#endif

**Comment by kinichiro** [comment] 2019-07-01 06:32
I found same kind of issue.
https://gitlab.freedesktop.org/ffontaine/libbsd/commit/1220b3b758030f1717558980d60ade9a33628383

Using pthread_atfork would solve this with uClibc on noMMU ?

>

**Comment by redbirdtek** [comment] 2019-07-01 07:32
> I found same kind of issue. https://gitlab.freedesktop.org/ffontaine/libbsd/commit/1220b3b758030f1717558980d60ade9a33628383 Using pthread_atfork would solve this with uClibc on noMMU ?
> […](#)

Yes, code-building pass if use pthread_atfork,hope someone can fix this issue in the master branch.

**Comment by kinichiro** [comment] 2019-07-01 12:08
Does this arc4random_linux.h patch work for you with uClibc ?
And regression tests succeed ?

```diff
--- crypto/compat/arc4random_linux.h.orig	Mon Jul  1 20:23:38 2019
+++ crypto/compat/arc4random_linux.h	Mon Jul  1 20:25:37 2019
@@ -32,7 +32,7 @@ static pthread_mutex_t arc4random_mtx = PTHREAD_MUTEX_
 #define _ARC4_LOCK()   pthread_mutex_lock(&arc4random_mtx)
 #define _ARC4_UNLOCK() pthread_mutex_unlock(&arc4random_mtx)
 
-#ifdef __GLIBC__
+#if defined(__GLIBC__) && !defined(__UCLIBC__)
 extern void *__dso_handle;
 extern int __register_atfork(void (*)(void), void(*)(void), void (*)(void), void *);
 #define _ARC4_ATFORK(f) __register_atfork(NULL, NULL, (f), __dso_handle)
```

I had tested this diff by travis-ci here, to verify before send this to upstream.
To test in travis-ci, I put this diff as patches/arc4random_linux.h.patch.
https://travis-ci.org/kinichiro/portable/builds/552726084

**Comment by busterb** [comment] 2019-07-09 11:25
That works fine for me. I think we intended for arc4random_linux.h to be able to work without any autoconf help since it lives upstream in the openbsd source, or I might have suggested a symbol check in the configuration phase instead.

**Comment by kinichiro** [comment] 2019-07-09 11:51
Shall I suggest upstream change for arc4random_linux.h in ML ?

**Comment by busterb** [comment] 2019-07-09 19:37
Sounds like the right thing to do. That'll fixup any other users as well on uclibc.

**Comment by kinichiro** [comment] 2019-07-12 11:03
@redbirdtek 
commit https://github.com/libressl-portable/openbsd/commit/8fa1a4289048e795eeb30fe1c9728350bd1efb5f fixes this issue.
I'll close this issue.

**Closed by kinichiro** 2019-07-12 11:03 UTC
