### ISSUE TITLE
regression in 3.4.1 (cert expiration check)

### ISSUE THREAD

**Issue by chipitsine** [libressl-portable/portable#697] opened 2021-11-05 03:37 UTC
in haproxy we run auto tests using both OpenSSL and LibreSSL.

when I use LibreSSL-3.4.1, some tests fail: https://github.com/chipitsine/haproxy/runs/4112541437?check_suite_focus=true

how to repro (for reg-tests/ssl/ssl_default_server.vtc):

```
git clone https://github.com/haproxy/haproxy
LIBRESSL_VERSION=3.4.1 ./scripts/build-ssl.sh
make CC=gcc TARGET=linux-glibc USE_OPENSSL=1 ADDLIB="-Wl,-rpath,${HOME}/opt/lib" SSL_LIB=${HOME}/opt/lib SSL_INC=${HOME}/opt/include
./scripts/build-vtest.sh
make reg-tests VTEST_PROGRAM=../vtest/vtest -- --debug reg-tests/ssl/ssl_default_server.vtc
```

**Comment by 4a6f656c** [comment] 2021-11-11 17:43
Thanks for the report - I've been able to reproduce the test failure and identify the root cause. We're currently working on a fix.

**Comment by chipitsine** [comment] 2021-11-11 17:57
I planned to dig deeper next weekend, but you were faster.
many thanks :)

**Comment by chipitsine** [comment] 2021-11-11 18:13
btw, there're several "vtc" failing. can you please check them after fix ?

```
Error: #    top  TEST reg-tests/ssl/set_ssl_cafile.vtc FAILED (0.141) exit=2
Error: #    top  TEST reg-tests/ssl/set_ssl_server_cert.vtc FAILED (0.172) exit=2
Error: #    top  TEST reg-tests/ssl/set_ssl_crlfile.vtc FAILED (0.515) exit=2
Error: #    top  TEST reg-tests/ssl/ssl_client_samples.vtc FAILED (0.137) exit=2
Error: #    top  TEST reg-tests/ssl/ssl_client_auth.vtc FAILED (0.164) exit=2
Error: #    top  TEST reg-tests/ssl/new_del_ssl_cafile.vtc FAILED (0.137) exit=2
Error: #    top  TEST reg-tests/ssl/new_del_ssl_crlfile.vtc FAILED (0.502) exit=2
Error: #    top  TEST reg-tests/ssl/ssl_default_server.vtc FAILED (0.187) exit=2
```

**Comment by 4a6f656c** [comment] 2021-11-30 07:57
This is effectively fixed in LibreSSL 3.4.2 - there is still one case where haproxy is expecting `X509_V_ERR_UNABLE_TO_VERIFY_LEAF_SIGNATURE` whereas we now return `X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT_LOCALLY` (in other words, we still return an error, just a different error).

The background is that we have replaced the broken single-chain verifier with a proper multi-chain verifier implementation and it has taken a long time and a lot of effort to get the behaviour (particularly with respect to the verify callback) to match. The corner case in which the legacy verifier returns `X509_V_ERR_UNABLE_TO_VERIFY_LEAF_SIGNATURE` is near impossible to replicate in the new verifier, plus it is not really even accurate/meaningful. As such, this difference is likely to remain.

**Closed by 4a6f656c** 2021-11-30 07:57 UTC

**Comment by chipitsine** [comment] 2021-12-01 05:08
I do not see explicit `X509_V_ERR_UNABLE_TO_VERIFY_LEAF_SIGNATURE` usage. 

```
[ilia@fedora haproxy]$ grep -r X509_V_ERR_UNABLE_TO_VERIFY_LEAF_SIGNATURE .
[ilia@fedora haproxy]$ 
```

can you please provide more info ?

**Comment by chipitsine** [comment] 2021-12-01 05:18
ok, I'll check `X509_V_ERR_UNABLE_TO_VERIFY_LEAF_SIGNATURE` and `X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT_LOCALLY` macros value and will back to it
