### ISSUE TITLE
LibreSSL 2.3.2: Eronneous "bad decrypt" message ?

### ISSUE THREAD

**Issue by udf2457** [libressl-portable/portable#179] opened 2016-03-16 16:54 UTC
LibreSSL 2.3.2
Linux ukc-bk04 3.13.0-79-generic #123-Ubuntu SMP Fri Feb 19 14:27:58 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

I have the attached shell scripts that do derived key encryption/decryption.

I am getting an erroneous "bad decrypt" message on decrypt.  However the mesage is not true, the hash digests of original and decrypted plaintexts are identical.

I have attached 6 files
decrypt.sh/encrypt.sh =  my scripts
decrypt_debug.txt = self explanatory
crypt_debug.txt = self explanatory
 proof.txt = the output I am getting
compile config.log

[crypt_debug.txt](https://github.com/libressl-portable/portable/files/176459/crypt_debug.txt)
[decrypt_debug.txt](https://github.com/libressl-portable/portable/files/176460/decrypt_debug.txt)
[decrypt.sh.txt](https://github.com/libressl-portable/portable/files/176463/decrypt.sh.txt)
[encrypt.sh.txt](https://github.com/libressl-portable/portable/files/176464/encrypt.sh.txt)
[proof.txt](https://github.com/libressl-portable/portable/files/176465/proof.txt)
[config.log.txt](https://github.com/libressl-portable/portable/files/176484/config.log.txt)

**Comment by leonklingele** [comment] 2016-03-16 16:59
Duplicate of https://github.com/libressl-portable/portable/issues/169

**Comment by 4a6f656c** [comment] 2016-07-06 02:42
See https://github.com/libressl-portable/portable/issues/79#issuecomment-93768605

**Closed by 4a6f656c** 2016-07-06 02:42 UTC
