### ISSUE TITLE
Verification failure for self-issued certificate chains

### ISSUE THREAD

**Issue by vctrex** [libressl-portable/portable#322] opened 2017-07-05 08:00 UTC
I need to connect to vpn server but what i've got are self-signed certificates and Libressl do not allow me to connect. Is there anything I can do about it? Right now I am totally hopless. Is there any .cnf file I can modify to make Verify allow those?

**Comment by vctrex** [comment] 2017-07-05 09:23
Wed Jul  5 11:22:22 2017 VERIFY ERROR: depth=0, error=self signed certificate: C=PA, ST=PA, L=Panama, O=NordVPN, OU=NordVPN, CN=za4.nordvpn.com, name=NordVPN, emailAddress=cert@nordvpn.com
Wed Jul  5 11:22:22 2017 OpenSSL: error:14007086:SSL routines:CONNECT_CR_CERT:certificate verify failed

openvpn error

**Comment by 4a6f656c** [comment] 2017-07-05 15:45
The issue is caused by a combination of things, one of which is the use of self-issued certificates (both the CA certificate and server certificate likely have the same CN) - the certificate chain verification code now handles self-signed certificates in a special way, however self-issued certificates are also being treated in the same manner.

Since it looks like this is not your server infrastructure, you're probably not able to use a self-signed server certificate that is not self-issued - if you can, then that is a fairly easy workaround. Otherwise you would need the following patch:

https://github.com/openbsd/src/commit/f675a65f9461f5c7535776900638276d4c7f6b3b

This will likely appear in a new libressl portable release, however I do not have an exact timeframe for this.

**Comment by busterb** [comment] 2017-07-13 10:11
This is fixed in the latest release. Thanks!

**Closed by busterb** 2017-07-13 10:11 UTC
