### ISSUE TITLE
Port to ARMv8 (arm64, aarch64)

### ISSUE THREAD

**Issue by vielmetti** [libressl-portable/portable#275] opened 2017-02-02 16:00 UTC
I'm working on a port of libressl-portable to ARMv8, and getting stuck on the build step.

I'm following the `cmake` instructions, and get this error at the very start:

```
CMake Error at CMakeLists.txt:14 (file):
  file failed to open for reading (No such file or directory):
  
    /mnt/src/libressl-portable/portable/ssl/VERSION
```

which seems pretty basic; thought I'd solve that one first....

**Comment by busterb** [comment] 2017-02-02 16:02
I'd start by reading the README file:

https://github.com/libressl-portable/portable#prerequisites-when-building-from-git

Also, I'm pretty sure it already builds on arm64, unless you're doing assembly bits.

**Comment by vielmetti** [comment] 2017-02-02 16:12
With that, success!

```
100% tests passed, 0 tests failed out of 58

Total Test time (real) =  79.83 sec
```

**Comment by vielmetti** [comment] 2017-02-02 16:12
I don't know if that's a good total test time or not....

**Comment by busterb** [comment] 2017-02-02 16:16
Well, a quad core xeon 4+ghz here beats that by an order of magnitude:

Total Test time (real) =   6.22 sec

**Comment by vielmetti** [comment] 2017-02-02 16:17
Yup, and this is a 96-core ARMv8 Cavium ThunderX machine from Packet (their 2A server), so this is not acceptable performance yet. I'l reopen.

**Comment by busterb** [comment] 2017-02-02 16:59
I also wouldn't call that the regression tests a performance test. This might all be IO bound for all I we know.

**Comment by vielmetti** [comment] 2017-02-02 19:23
@busterb - is there some performance suite that you can suggest? My working assumption is that the code doesn't use the ARMv8 hardware instructions that support crypto.

**Comment by busterb** [comment] 2017-02-02 19:47
`openssl speed` ? I'd suggest you reach out to Patrick Wildt, who is doing the aarch64 port for OpenBSD. Something like new architecture support should probably flow from OpenBSD out to portable. Here's the latest status: http://undeadly.org/cgi?action=article&sid=20170131101827

**Comment by bob-beck** [comment] 2017-02-05 01:32
You don't need a working assumption for that, unless you have made changes locally to 
use this, the assembler stuff is not enabled in LibreSSL for ARM today.  Speaking from
experience with other armv8 platforms and OpenSSL, you should see "openssl speed" numbers
within the same order of magnitude as you see on something on amd64 type arch's with
crypto support and assembly implementations that make use of them, if they were in use. 

We are not averse to enabling them, but we probably won't do so by default without
a reasonable way to test them and to be confident to some degree of their safety. Patches
and test reports are of course, welcome.

**Comment by busterb** [comment] 2017-03-30 00:31
I think this discussion is best moved to tech@ for the 6.2 openbsd release train that will happen after tree unlock, since this is not a portable-only issue. Will close this, since you can actually build on aarch64 today.

**Closed by busterb** 2017-03-30 00:31 UTC
