### ISSUE TITLE
error building on osx 10.12.6

### ISSUE THREAD

**Issue by snjagor** [libressl-portable/portable#418] opened 2018-04-11 02:12 UTC
Building libressl-2.7.2 from src with:
`./configure --disable-dependency-tracking --prefix=/usr/local/libressl --disable-silent-rules`

I get errors with `sudo make install` :
`install: /usr/local/libressl/share/man/man3/OCSP_CRLID_new.3: Too many levels of symbolic links`
`make[2]: *** [install-man3] Error 71`
`make[1]: *** [install-am] Error 2`
`make: *** [install-recursive] Error 1
`

All tests in `make check` pass...

**Comment by busterb** [comment] 2018-04-11 02:25
It’s because you have a case-preserving but case-insensitive filesystem, and OCSP_CRLID_new and OCSP_crlID_new are conflicting.

**Comment by snjagor** [comment] 2018-04-11 03:00
I see, is there a configure option so libressl can workaround this? or should i just rename the file?

**Comment by snjagor** [comment] 2018-04-11 04:54
I ended up deleting the symlinks OCSP_crlID_new.3 and OCSP_CRLID_free.3  in /usr/local/libressl/share/man/man3/  and `make install` installed successfully. 

Probably checking for existing installs and removing these files would be a good idea?

**Comment by kinichiro** [comment] 2018-05-02 15:54
Issue #231 appears to be caused by the same reason.

**Comment by busterb** [comment] 2018-06-17 02:31
Fixed in b78f2939398db49bb1dfabaa48529d11ae687e20

**Closed by busterb** 2018-06-17 02:31 UTC
