### ISSUE TITLE
new coverity findings

### ISSUE THREAD

**Issue by chipitsine** [libressl-portable/portable#787] opened 2022-09-06 04:02 UTC
@4a6f656c , can you have a look please ?
them look similar to https://github.com/libressl-portable/portable/issues/778

```
New defect(s) Reported-by: Coverity Scan
Showing 20 of 25 defect(s)


** CID 356685:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_camellia.c: 664 in camellia_256_cfb1_cipher()


________________________________________________________________________________________________________
*** CID 356685:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_camellia.c: 664 in camellia_256_cfb1_cipher()
658             chunk >>= 3;
659     
660             if (inl < chunk)
661                     chunk = inl;
662     
663             while (inl && inl >= chunk) {
>>>     CID 356685:  Memory - corruptions  (OVERRUN)
>>>     Calling "Camellia_cfb1_encrypt" with "in" and "(long)((1 && !(ctx->flags & 0x2000UL)) ? inl * 8UL : inl)" is suspicious because of the very large index, 4611686018427387904. The index may be due to a negative parameter being interpreted as unsigned. [Note: The source code implementation of the function has been overridden by a builtin model.]
664                     Camellia_cfb1_encrypt(in, out, (long)((1 == 1) && !(ctx->flags & EVP_CIPH_FLAG_LENGTH_BITS) ? inl * 8 : inl), &((EVP_CAMELLIA_KEY *)ctx->cipher_data)->ks, ctx->iv, &ctx->num, ctx->encrypt);
665                     inl -= chunk;
666                     in += chunk;
667                     out += chunk;
668                     if (inl < chunk)
669                             chunk = inl;

** CID 356684:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_camellia.c: 432 in camellia_256_cfb128_cipher()


________________________________________________________________________________________________________
*** CID 356684:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_camellia.c: 432 in camellia_256_cfb128_cipher()
426             size_t chunk = EVP_MAXCHUNK;
427     
428             if (inl < chunk)
429                     chunk = inl;
430     
431             while (inl && inl >= chunk) {
>>>     CID 356684:  Memory - corruptions  (OVERRUN)
>>>     Calling "Camellia_cfb128_encrypt" with "in" and "(long)inl" is suspicious because of the very large index, 4611686018427387904. The index may be due to a negative parameter being interpreted as unsigned. [Note: The source code implementation of the function has been overridden by a builtin model.]
432                     Camellia_cfb128_encrypt(in, out, (long)inl, &((EVP_CAMELLIA_KEY *)ctx->cipher_data)->ks, ctx->iv, &ctx->num, ctx->encrypt);
433                     inl -= chunk;
434                     in += chunk;
435                     out += chunk;
436                     if (inl < chunk)
437                             chunk = inl;

** CID 356683:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_camellia.c: 620 in camellia_192_cfb1_cipher()


________________________________________________________________________________________________________
*** CID 356683:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_camellia.c: 620 in camellia_192_cfb1_cipher()
614             chunk >>= 3;
615     
616             if (inl < chunk)
617                     chunk = inl;
618     
619             while (inl && inl >= chunk) {
>>>     CID 356683:  Memory - corruptions  (OVERRUN)
>>>     Calling "Camellia_cfb1_encrypt" with "out" and "(long)((1 && !(ctx->flags & 0x2000UL)) ? inl * 8UL : inl)" is suspicious because of the very large index, 4611686018427387904. The index may be due to a negative parameter being interpreted as unsigned. [Note: The source code implementation of the function has been overridden by a builtin model.]
620                     Camellia_cfb1_encrypt(in, out, (long)((1 == 1) && !(ctx->flags & EVP_CIPH_FLAG_LENGTH_BITS) ? inl * 8 : inl), &((EVP_CAMELLIA_KEY *)ctx->cipher_data)->ks, ctx->iv, &ctx->num, ctx->encrypt);
621                     inl -= chunk;
622                     in += chunk;
623                     out += chunk;
624                     if (inl < chunk)
625                             chunk = inl;

** CID 356682:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_cast.c: 117 in cast5_cfb64_cipher()


________________________________________________________________________________________________________
*** CID 356682:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_cast.c: 117 in cast5_cfb64_cipher()
111                     return 0;
112     
113             if (inl < chunk)
114                     chunk = inl;
115     
116             while (inl && inl >= chunk) {
>>>     CID 356682:  Memory - corruptions  (OVERRUN)
>>>     Calling "CAST_cfb64_encrypt" with "out" and "(long)inl" is suspicious because of the very large index, 4611686018427387904. The index may be due to a negative parameter being interpreted as unsigned. [Note: The source code implementation of the function has been overridden by a builtin model.]
117                     CAST_cfb64_encrypt(in, out, (long)inl, &((EVP_CAST_KEY *)ctx->cipher_data)->ks, ctx->iv, &ctx->num, ctx->encrypt);
118                     inl -= chunk;
119                     in += chunk;
120                     out += chunk;
121                     if (inl < chunk)
122                             chunk = inl;

** CID 356681:    (BAD_SIZEOF)
/home/runner/work/portable/portable/tests/rc4_test.c: 379 in rc4_test()
/home/runner/work/portable/portable/tests/rc4_test.c: 416 in rc4_test()


________________________________________________________________________________________________________
*** CID 356681:    (BAD_SIZEOF)
/home/runner/work/portable/portable/tests/rc4_test.c: 379 in rc4_test()
373                     if (!EVP_EncryptInit(ctx, cipher, rt->key, NULL)) {
374                             fprintf(stderr, "FAIL: EVP_EncryptInit failed\n");
375                             goto failed;
376                     }
377     
378                     for (j = 0; j < rt->len;) {
>>>     CID 356681:    (BAD_SIZEOF)
>>>     Taking the size of arithmetic expression "rt->len / 2" is suspicious.
379                             in_len = arc4random_uniform(sizeof(rt->len / 2));
380                             if (in_len > rt->len - j)
381                                     in_len = rt->len - j;
382     
383                             if (!EVP_EncryptUpdate(ctx, out + j, &out_len,
384                                 rt->in + j, in_len)) {
/home/runner/work/portable/portable/tests/rc4_test.c: 416 in rc4_test()
410                     if (!EVP_DecryptInit(ctx, cipher, rt->key, NULL)) {
411                             fprintf(stderr, "FAIL: EVP_DecryptInit failed\n");
412                             goto failed;
413                     }
414     
415                     for (j = 0; j < rt->len;) {
>>>     CID 356681:    (BAD_SIZEOF)
>>>     Taking the size of arithmetic expression "rt->len / 2" is suspicious.
416                             in_len = arc4random_uniform(sizeof(rt->len / 2));
417                             if (in_len > rt->len - j)
418                                     in_len = rt->len - j;
419     
420                             if (!EVP_DecryptUpdate(ctx, out + j, &out_len,
421                                 rt->in + j, in_len)) {

** CID 356680:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_camellia.c: 749 in camellia_192_cfb8_cipher()


________________________________________________________________________________________________________
*** CID 356680:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_camellia.c: 749 in camellia_192_cfb8_cipher()
743             size_t chunk = EVP_MAXCHUNK;
744     
745             if (inl < chunk)
746                     chunk = inl;
747     
748             while (inl && inl >= chunk) {
>>>     CID 356680:  Memory - corruptions  (OVERRUN)
>>>     Calling "Camellia_cfb8_encrypt" with "in" and "(long)inl" is suspicious because of the very large index, 4611686018427387904. The index may be due to a negative parameter being interpreted as unsigned. [Note: The source code implementation of the function has been overridden by a builtin model.]
749                     Camellia_cfb8_encrypt(in, out, (long)inl, &((EVP_CAMELLIA_KEY *)ctx->cipher_data)->ks, ctx->iv, &ctx->num, ctx->encrypt);
750                     inl -= chunk;
751                     in += chunk;
752                     out += chunk;
753                     if (inl < chunk)
754                             chunk = inl;

** CID 356679:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_cast.c: 117 in cast5_cfb64_cipher()


________________________________________________________________________________________________________
*** CID 356679:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_cast.c: 117 in cast5_cfb64_cipher()
111                     return 0;
112     
113             if (inl < chunk)
114                     chunk = inl;
115     
116             while (inl && inl >= chunk) {
>>>     CID 356679:  Memory - corruptions  (OVERRUN)
>>>     Calling "CAST_cfb64_encrypt" with "in" and "(long)inl" is suspicious because of the very large index, 4611686018427387904. The index may be due to a negative parameter being interpreted as unsigned. [Note: The source code implementation of the function has been overridden by a builtin model.]
117                     CAST_cfb64_encrypt(in, out, (long)inl, &((EVP_CAST_KEY *)ctx->cipher_data)->ks, ctx->iv, &ctx->num, ctx->encrypt);
118                     inl -= chunk;
119                     in += chunk;
120                     out += chunk;
121                     if (inl < chunk)
122                             chunk = inl;

** CID 356678:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_camellia.c: 576 in camellia_128_cfb1_cipher()


________________________________________________________________________________________________________
*** CID 356678:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_camellia.c: 576 in camellia_128_cfb1_cipher()
570             chunk >>= 3;
571     
572             if (inl < chunk)
573                     chunk = inl;
574     
575             while (inl && inl >= chunk) {
>>>     CID 356678:  Memory - corruptions  (OVERRUN)
>>>     Calling "Camellia_cfb1_encrypt" with "out" and "(long)((1 && !(ctx->flags & 0x2000UL)) ? inl * 8UL : inl)" is suspicious because of the very large index, 4611686018427387904. The index may be due to a negative parameter being interpreted as unsigned. [Note: The source code implementation of the function has been overridden by a builtin model.]
576                     Camellia_cfb1_encrypt(in, out, (long)((1 == 1) && !(ctx->flags & EVP_CIPH_FLAG_LENGTH_BITS) ? inl * 8 : inl), &((EVP_CAMELLIA_KEY *)ctx->cipher_data)->ks, ctx->iv, &ctx->num, ctx->encrypt);
577                     inl -= chunk;
578                     in += chunk;
579                     out += chunk;
580                     if (inl < chunk)
581                             chunk = inl;

** CID 356677:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_camellia.c: 664 in camellia_256_cfb1_cipher()


________________________________________________________________________________________________________
*** CID 356677:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_camellia.c: 664 in camellia_256_cfb1_cipher()
658             chunk >>= 3;
659     
660             if (inl < chunk)
661                     chunk = inl;
662     
663             while (inl && inl >= chunk) {
>>>     CID 356677:  Memory - corruptions  (OVERRUN)
>>>     Calling "Camellia_cfb1_encrypt" with "out" and "(long)((1 && !(ctx->flags & 0x2000UL)) ? inl * 8UL : inl)" is suspicious because of the very large index, 4611686018427387904. The index may be due to a negative parameter being interpreted as unsigned. [Note: The source code implementation of the function has been overridden by a builtin model.]
664                     Camellia_cfb1_encrypt(in, out, (long)((1 == 1) && !(ctx->flags & EVP_CIPH_FLAG_LENGTH_BITS) ? inl * 8 : inl), &((EVP_CAMELLIA_KEY *)ctx->cipher_data)->ks, ctx->iv, &ctx->num, ctx->encrypt);
665                     inl -= chunk;
666                     in += chunk;
667                     out += chunk;
668                     if (inl < chunk)
669                             chunk = inl;

** CID 356676:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_camellia.c: 791 in camellia_256_cfb8_cipher()


________________________________________________________________________________________________________
*** CID 356676:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_camellia.c: 791 in camellia_256_cfb8_cipher()
785             size_t chunk = EVP_MAXCHUNK;
786     
787             if (inl < chunk)
788                     chunk = inl;
789     
790             while (inl && inl >= chunk) {
>>>     CID 356676:  Memory - corruptions  (OVERRUN)
>>>     Calling "Camellia_cfb8_encrypt" with "in" and "(long)inl" is suspicious because of the very large index, 4611686018427387904. The index may be due to a negative parameter being interpreted as unsigned. [Note: The source code implementation of the function has been overridden by a builtin model.]
791                     Camellia_cfb8_encrypt(in, out, (long)inl, &((EVP_CAMELLIA_KEY *)ctx->cipher_data)->ks, ctx->iv, &ctx->num, ctx->encrypt);
792                     inl -= chunk;
793                     in += chunk;
794                     out += chunk;
795                     if (inl < chunk)
796                             chunk = inl;

** CID 356675:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_camellia.c: 274 in camellia_192_cfb128_cipher()


________________________________________________________________________________________________________
*** CID 356675:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_camellia.c: 274 in camellia_192_cfb128_cipher()
268             size_t chunk = EVP_MAXCHUNK;
269     
270             if (inl < chunk)
271                     chunk = inl;
272     
273             while (inl && inl >= chunk) {
>>>     CID 356675:  Memory - corruptions  (OVERRUN)
>>>     Calling "Camellia_cfb128_encrypt" with "in" and "(long)inl" is suspicious because of the very large index, 4611686018427387904. The index may be due to a negative parameter being interpreted as unsigned. [Note: The source code implementation of the function has been overridden by a builtin model.]
274                     Camellia_cfb128_encrypt(in, out, (long)inl, &((EVP_CAMELLIA_KEY *)ctx->cipher_data)->ks, ctx->iv, &ctx->num, ctx->encrypt);
275                     inl -= chunk;
276                     in += chunk;
277                     out += chunk;
278                     if (inl < chunk)
279                             chunk = inl;

** CID 356674:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_camellia.c: 274 in camellia_192_cfb128_cipher()


________________________________________________________________________________________________________
*** CID 356674:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_camellia.c: 274 in camellia_192_cfb128_cipher()
268             size_t chunk = EVP_MAXCHUNK;
269     
270             if (inl < chunk)
271                     chunk = inl;
272     
273             while (inl && inl >= chunk) {
>>>     CID 356674:  Memory - corruptions  (OVERRUN)
>>>     Calling "Camellia_cfb128_encrypt" with "out" and "(long)inl" is suspicious because of the very large index, 4611686018427387904. The index may be due to a negative parameter being interpreted as unsigned. [Note: The source code implementation of the function has been overridden by a builtin model.]
274                     Camellia_cfb128_encrypt(in, out, (long)inl, &((EVP_CAMELLIA_KEY *)ctx->cipher_data)->ks, ctx->iv, &ctx->num, ctx->encrypt);
275                     inl -= chunk;
276                     in += chunk;
277                     out += chunk;
278                     if (inl < chunk)
279                             chunk = inl;

** CID 356673:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_camellia.c: 749 in camellia_192_cfb8_cipher()


________________________________________________________________________________________________________
*** CID 356673:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_camellia.c: 749 in camellia_192_cfb8_cipher()
743             size_t chunk = EVP_MAXCHUNK;
744     
745             if (inl < chunk)
746                     chunk = inl;
747     
748             while (inl && inl >= chunk) {
>>>     CID 356673:  Memory - corruptions  (OVERRUN)
>>>     Calling "Camellia_cfb8_encrypt" with "out" and "(long)inl" is suspicious because of the very large index, 4611686018427387904. The index may be due to a negative parameter being interpreted as unsigned. [Note: The source code implementation of the function has been overridden by a builtin model.]
749                     Camellia_cfb8_encrypt(in, out, (long)inl, &((EVP_CAMELLIA_KEY *)ctx->cipher_data)->ks, ctx->iv, &ctx->num, ctx->encrypt);
750                     inl -= chunk;
751                     in += chunk;
752                     out += chunk;
753                     if (inl < chunk)
754                             chunk = inl;

** CID 356672:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_camellia.c: 620 in camellia_192_cfb1_cipher()


________________________________________________________________________________________________________
*** CID 356672:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_camellia.c: 620 in camellia_192_cfb1_cipher()
614             chunk >>= 3;
615     
616             if (inl < chunk)
617                     chunk = inl;
618     
619             while (inl && inl >= chunk) {
>>>     CID 356672:  Memory - corruptions  (OVERRUN)
>>>     Calling "Camellia_cfb1_encrypt" with "in" and "(long)((1 && !(ctx->flags & 0x2000UL)) ? inl * 8UL : inl)" is suspicious because of the very large index, 4611686018427387904. The index may be due to a negative parameter being interpreted as unsigned. [Note: The source code implementation of the function has been overridden by a builtin model.]
620                     Camellia_cfb1_encrypt(in, out, (long)((1 == 1) && !(ctx->flags & EVP_CIPH_FLAG_LENGTH_BITS) ? inl * 8 : inl), &((EVP_CAMELLIA_KEY *)ctx->cipher_data)->ks, ctx->iv, &ctx->num, ctx->encrypt);
621                     inl -= chunk;
622                     in += chunk;
623                     out += chunk;
624                     if (inl < chunk)
625                             chunk = inl;

** CID 356671:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_camellia.c: 791 in camellia_256_cfb8_cipher()


________________________________________________________________________________________________________
*** CID 356671:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_camellia.c: 791 in camellia_256_cfb8_cipher()
785             size_t chunk = EVP_MAXCHUNK;
786     
787             if (inl < chunk)
788                     chunk = inl;
789     
790             while (inl && inl >= chunk) {
>>>     CID 356671:  Memory - corruptions  (OVERRUN)
>>>     Calling "Camellia_cfb8_encrypt" with "out" and "(long)inl" is suspicious because of the very large index, 4611686018427387904. The index may be due to a negative parameter being interpreted as unsigned. [Note: The source code implementation of the function has been overridden by a builtin model.]
791                     Camellia_cfb8_encrypt(in, out, (long)inl, &((EVP_CAMELLIA_KEY *)ctx->cipher_data)->ks, ctx->iv, &ctx->num, ctx->encrypt);
792                     inl -= chunk;
793                     in += chunk;
794                     out += chunk;
795                     if (inl < chunk)
796                             chunk = inl;

** CID 356670:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_camellia.c: 576 in camellia_128_cfb1_cipher()


________________________________________________________________________________________________________
*** CID 356670:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_camellia.c: 576 in camellia_128_cfb1_cipher()
570             chunk >>= 3;
571     
572             if (inl < chunk)
573                     chunk = inl;
574     
575             while (inl && inl >= chunk) {
>>>     CID 356670:  Memory - corruptions  (OVERRUN)
>>>     Calling "Camellia_cfb1_encrypt" with "in" and "(long)((1 && !(ctx->flags & 0x2000UL)) ? inl * 8UL : inl)" is suspicious because of the very large index, 4611686018427387904. The index may be due to a negative parameter being interpreted as unsigned. [Note: The source code implementation of the function has been overridden by a builtin model.]
576                     Camellia_cfb1_encrypt(in, out, (long)((1 == 1) && !(ctx->flags & EVP_CIPH_FLAG_LENGTH_BITS) ? inl * 8 : inl), &((EVP_CAMELLIA_KEY *)ctx->cipher_data)->ks, ctx->iv, &ctx->num, ctx->encrypt);
577                     inl -= chunk;
578                     in += chunk;
579                     out += chunk;
580                     if (inl < chunk)
581                             chunk = inl;

** CID 356669:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_camellia.c: 116 in camellia_128_cfb128_cipher()


________________________________________________________________________________________________________
*** CID 356669:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_camellia.c: 116 in camellia_128_cfb128_cipher()
110             size_t chunk = EVP_MAXCHUNK;
111     
112             if (inl < chunk)
113                     chunk = inl;
114     
115             while (inl && inl >= chunk) {
>>>     CID 356669:  Memory - corruptions  (OVERRUN)
>>>     Calling "Camellia_cfb128_encrypt" with "out" and "(long)inl" is suspicious because of the very large index, 4611686018427387904. The index may be due to a negative parameter being interpreted as unsigned. [Note: The source code implementation of the function has been overridden by a builtin model.]
116                     Camellia_cfb128_encrypt(in, out, (long)inl, &((EVP_CAMELLIA_KEY *)ctx->cipher_data)->ks, ctx->iv, &ctx->num, ctx->encrypt);
117                     inl -= chunk;
118                     in += chunk;
119                     out += chunk;
120                     if (inl < chunk)
121                             chunk = inl;

** CID 356668:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_camellia.c: 707 in camellia_128_cfb8_cipher()


________________________________________________________________________________________________________
*** CID 356668:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_camellia.c: 707 in camellia_128_cfb8_cipher()
701             size_t chunk = EVP_MAXCHUNK;
702     
703             if (inl < chunk)
704                     chunk = inl;
705     
706             while (inl && inl >= chunk) {
>>>     CID 356668:  Memory - corruptions  (OVERRUN)
>>>     Calling "Camellia_cfb8_encrypt" with "out" and "(long)inl" is suspicious because of the very large index, 4611686018427387904. The index may be due to a negative parameter being interpreted as unsigned. [Note: The source code implementation of the function has been overridden by a builtin model.]
707                     Camellia_cfb8_encrypt(in, out, (long)inl, &((EVP_CAMELLIA_KEY *)ctx->cipher_data)->ks, ctx->iv, &ctx->num, ctx->encrypt);
708                     inl -= chunk;
709                     in += chunk;
710                     out += chunk;
711                     if (inl < chunk)
712                             chunk = inl;

** CID 356667:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_camellia.c: 707 in camellia_128_cfb8_cipher()


________________________________________________________________________________________________________
*** CID 356667:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_camellia.c: 707 in camellia_128_cfb8_cipher()
701             size_t chunk = EVP_MAXCHUNK;
702     
703             if (inl < chunk)
704                     chunk = inl;
705     
706             while (inl && inl >= chunk) {
>>>     CID 356667:  Memory - corruptions  (OVERRUN)
>>>     Calling "Camellia_cfb8_encrypt" with "in" and "(long)inl" is suspicious because of the very large index, 4611686018427387904. The index may be due to a negative parameter being interpreted as unsigned. [Note: The source code implementation of the function has been overridden by a builtin model.]
707                     Camellia_cfb8_encrypt(in, out, (long)inl, &((EVP_CAMELLIA_KEY *)ctx->cipher_data)->ks, ctx->iv, &ctx->num, ctx->encrypt);
708                     inl -= chunk;
709                     in += chunk;
710                     out += chunk;
711                     if (inl < chunk)
712                             chunk = inl;

** CID 356666:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_camellia.c: 116 in camellia_128_cfb128_cipher()


________________________________________________________________________________________________________
*** CID 356666:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_camellia.c: 116 in camellia_128_cfb128_cipher()
110             size_t chunk = EVP_MAXCHUNK;
111     
112             if (inl < chunk)
113                     chunk = inl;
114     
115             while (inl && inl >= chunk) {
>>>     CID 356666:  Memory - corruptions  (OVERRUN)
>>>     Calling "Camellia_cfb128_encrypt" with "in" and "(long)inl" is suspicious because of the very large index, 4611686018427387904. The index may be due to a negative parameter being interpreted as unsigned. [Note: The source code implementation of the function has been overridden by a builtin model.]
116                     Camellia_cfb128_encrypt(in, out, (long)inl, &((EVP_CAMELLIA_KEY *)ctx->cipher_data)->ks, ctx->iv, &ctx->num, ctx->encrypt);
117                     inl -= chunk;
118                     in += chunk;
119                     out += chunk;
120                     if (inl < chunk)
121                             chunk = inl;
```

**Comment by 4a6f656c** [comment] 2022-09-10 18:00
Thanks - this is effectively part of issue #778, which I'm still addressing. I'll mark this as a duplicate.

**Comment by 4a6f656c** [comment] 2022-09-10 18:04
Duplicate of #778.

**Closed by 4a6f656c** 2022-09-10 18:04 UTC
