### ISSUE TITLE
secure.ssa.gov inaccessable via libressl

### ISSUE THREAD

**Issue by toddfries** [libressl-portable/portable#206] opened 2016-07-08 08:54 UTC
```
$ openssl s_client -connect secure.ssa.gov:443 -debug 
CONNECTED(00000003)
write to 0x1b0274358180 [0x1b02476d6000] (326 bytes => 326 (0x146))
0000 - 16 03 01 01 41 01 00 01-3d 03 03 f2 6a ae 3f bb   ....A...=...j.?.
0010 - f8 0f 94 74 a3 51 fb b3-1c e5 92 fd 09 c4 f5 10   ...t.Q..........
0020 - be 8e 39 fe a6 c4 25 d4-b2 34 43 00 00 a0 c0 30   ..9...%..4C....0
0030 - c0 2c c0 28 c0 24 c0 14-c0 0a 00 a3 00 9f 00 6b   .,.(.$.........k
0040 - 00 6a 00 39 00 38 cc a9-cc a8 cc aa cc 14 cc 13   .j.9.8..........
0050 - cc 15 ff 85 00 c4 00 c3-00 88 00 87 00 81 c0 32   ...............2
0060 - c0 2e c0 2a c0 26 c0 0f-c0 05 00 9d 00 3d 00 35   ...*.&.......=.5
0070 - 00 c0 00 84 c0 2f c0 2b-c0 27 c0 23 c0 13 c0 09   ...../.+.'.#....
0080 - 00 a2 00 9e 00 67 00 40-00 33 00 32 00 be 00 bd   .....g.@.3.2....
0090 - 00 45 00 44 c0 31 c0 2d-c0 29 c0 25 c0 0e c0 04   .E.D.1.-.).%....
00a0 - 00 9c 00 3c 00 2f 00 ba-00 41 00 07 c0 11 c0 07   ...<./...A......
00b0 - c0 0c c0 02 00 05 00 04-c0 12 c0 08 00 16 00 13   ................
00c0 - c0 0d c0 03 00 0a 00 15-00 12 00 09 00 ff 01 00   ................
00d0 - 00 74 00 0b 00 04 03 00-01 02 00 0a 00 3a 00 38   .t...........:.8
00e0 - 00 0e 00 0d 00 19 00 1c-00 0b 00 0c 00 1b 00 18   ................
00f0 - 00 09 00 0a 00 1a 00 16-00 17 00 08 00 06 00 07   ................
0100 - 00 14 00 15 00 04 00 05-00 12 00 13 00 01 00 02   ................
0110 - 00 03 00 0f 00 10 00 11-00 23 00 00 00 0d 00 26   .........#.....&
0120 - 00 24 06 01 06 02 06 03-ef ef 05 01 05 02 05 03   .$..............
0130 - 04 01 04 02 04 03 ee ee-ed ed 03 01 03 02 03 03   ................
0140 - 02 01 02 02 02 03                                 ......
```
... and there it hangs, no more output.

```
$ eopenssl s_client -connect secure.ssa.gov:443 -debug 
CONNECTED(00000003)
write to 0xf49f044fc80 [0xf49d69b4000] (307 bytes => 307 (0x133))
0000 - 16 03 01 01 2e 01 00 01-2a 03 03 e6 13 47 f1 32   ........*....G.2
0010 - be c0 7f 48 c0 66 8f 79-9f b2 c1 b9 52 9b f7 fe   ...H.f.y....R...
0020 - b0 10 32 f1 f2 e1 d5 a6-d7 29 5c 00 00 ac c0 30   ..2......)\....0
0030 - c0 2c c0 28 c0 24 c0 14-c0 0a 00 a5 00 a3 00 a1   .,.(.$..........
0040 - 00 9f 00 6b 00 6a 00 69-00 68 00 39 00 38 00 37   ...k.j.i.h.9.8.7
0050 - 00 36 00 88 00 87 00 86-00 85 c0 32 c0 2e c0 2a   .6.........2...*
0060 - c0 26 c0 0f c0 05 00 9d-00 3d 00 35 00 84 c0 2f   .&.......=.5.../
0070 - c0 2b c0 27 c0 23 c0 13-c0 09 00 a4 00 a2 00 a0   .+.'.#..........
0080 - 00 9e 00 67 00 40 00 3f-00 3e 00 33 00 32 00 31   ...g.@.?.>.3.2.1
0090 - 00 30 00 9a 00 99 00 98-00 97 00 45 00 44 00 43   .0.........E.D.C
00a0 - 00 42 c0 31 c0 2d c0 29-c0 25 c0 0e c0 04 00 9c   .B.1.-.).%......
00b0 - 00 3c 00 2f 00 96 00 41-00 07 c0 11 c0 07 c0 0c   .<./...A........
00c0 - c0 02 00 05 00 04 c0 12-c0 08 00 16 00 13 00 10   ................
00d0 - 00 0d c0 0d c0 03 00 0a-00 ff 01 00 00 55 00 0b   .............U..
00e0 - 00 04 03 00 01 02 00 0a-00 1c 00 1a 00 17 00 19   ................
00f0 - 00 1c 00 1b 00 18 00 1a-00 16 00 0e 00 0d 00 0b   ................
0100 - 00 0c 00 09 00 0a 00 23-00 00 00 0d 00 20 00 1e   .......#..... ..
0110 - 06 01 06 02 06 03 05 01-05 02 05 03 04 01 04 02   ................
0120 - 04 03 03 01 03 02 03 03-02 01 02 02 02 03 00 0f   ................
0130 - 00 01 01                                          ...
read from 0xf49f044fc80 [0xf49edbe8000] (7 bytes => 7 (0x7))
0000 - 16 03 01 10 5e 02                                 ....^.
0007 - <SPACES/NULS>
read from 0xf49f044fc80 [0xf49edbe800a] (4188 bytes => 2889 (0xB49))
0000 - 00 4d 03 01 00 00 00 57-b3 88 ef 3c 04 25 f3 e5   .M.....W...<.%..
0010 - 31 df 85 97 27 19 40 5b-9e 21 ae 59 47 f1 f3 65   1...'.@[.!.YG..e
0020 - 13 ce 10 b6 20 00 00 02-3f e0 37 47 4e 0e 05 b7   .... ...?.7GN...
0030 - 81 69 7f 09 97 72 30 7d-37 58 58 58 58 57 7f 69   .i...r0}7XXXXW.i
```
... and exchange continues to completion, ultimately settling on:

```
0020 - 98 56 6b fd 83 b6 0b a3-3f 45 8a 10 cf 81 46 57   .Vk.....?E....FW
---
Certificate chain
 0 s:/businessCategory=Government Entity/jurisdictionC=US/serialNumber=Government Entity/street=6401 Security Blvd./postalCode=21235/C=US/ST=Maryland/L=Balitmore/O=Social Security Administration/CN=secure.ssa.gov
   i:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 Extended Validation Server CA
 1 s:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 Extended Validation Server CA
   i:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert High Assurance EV Root CA
 2 s:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert High Assurance EV Root CA
   i:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert High Assurance EV Root CA
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIHcjCCBlqgAwIBAgIQDZHHbkNuVxmA97ujmNv25jANBgkqhkiG9w0BAQsFADB1
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
d3cuZGlnaWNlcnQuY29tMTQwMgYDVQQDEytEaWdpQ2VydCBTSEEyIEV4dGVuZGVk
IFZhbGlkYXRpb24gU2VydmVyIENBMB4XDTE0MDcxNTAwMDAwMFoXDTE2MDkzMDEy
MDAwMFowgfExGjAYBgNVBA8MEUdvdmVybm1lbnQgRW50aXR5MRMwEQYLKwYBBAGC
NzwCAQMTAlVTMRowGAYDVQQFExFHb3Zlcm5tZW50IEVudGl0eTEcMBoGA1UECRMT
NjQwMSBTZWN1cml0eSBCbHZkLjEOMAwGA1UEERMFMjEyMzUxCzAJBgNVBAYTAlVT
MREwDwYDVQQIEwhNYXJ5bGFuZDESMBAGA1UEBxMJQmFsaXRtb3JlMScwJQYDVQQK
Ex5Tb2NpYWwgU2VjdXJpdHkgQWRtaW5pc3RyYXRpb24xFzAVBgNVBAMTDnNlY3Vy
ZS5zc2EuZ292MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvdYqZWE3
eA35AqkECCjD1G6K0tMm0ElBwGmrkFZU0iJTk+rPQ5DKtuksDp6gg6rpRHoZg4vE
0pH0So1l7sjQN4/B7Ky6kBEloilqzyAqJ9gJWzAcaBVvj3eCrt/PAtfWDE5iRrmU
Pklho8i2TVdigBJbsj/UrrBPxFz0gvDslqYCa8+YY0U8qFoURxMxYg/3aY1oKVnN
zZ1tUutAkxufJFzdtbFSq6Ngna1d/olB8xewslyMDiy/PveY0yEMWcEJDwbGLDuz
T3lFPpsPuLZcngCXUOmNmKU/WDXNKxsZwaHjto5OWCsmvPmNvwrr52a3cdh13sw8
MX7kHoZj8vj/OQIDAQABo4IDfzCCA3swHwYDVR0jBBgwFoAUPdNQpdagre7zSmAK
ZdMh1Pj41g8wHQYDVR0OBBYEFDvwVXGrZqWqGjZR9D1Yitzz+k5oMDUGA1UdEQQu
MCyCDnNlY3VyZS5zc2EuZ292gg1yZW1hYy5zc2EuZ292ggt0bHMuc3NhLmdvdjAO
BgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMHUG
A1UdHwRuMGwwNKAyoDCGLmh0dHA6Ly9jcmwzLmRpZ2ljZXJ0LmNvbS9zaGEyLWV2
LXNlcnZlci1nMS5jcmwwNKAyoDCGLmh0dHA6Ly9jcmw0LmRpZ2ljZXJ0LmNvbS9z
aGEyLWV2LXNlcnZlci1nMS5jcmwwQgYDVR0gBDswOTA3BglghkgBhv1sAgEwKjAo
BggrBgEFBQcCARYcaHR0cHM6Ly93d3cuZGlnaWNlcnQuY29tL0NQUzCBiAYIKwYB
BQUHAQEEfDB6MCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5kaWdpY2VydC5jb20w
UgYIKwYBBQUHMAKGRmh0dHA6Ly9jYWNlcnRzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2Vy
dFNIQTJFeHRlbmRlZFZhbGlkYXRpb25TZXJ2ZXJDQS5jcnQwDAYDVR0TAQH/BAIw
ADCCAX0GCisGAQQB1nkCBAIEggFtBIIBaQFnAHUApLkJkLQYWBSHuxOizGdwCjw1
mAT5G9+443fNDsgN3BAAAAFMdoBZ7QAABAMARjBEAiBshrd9X8yCZmkgskAf2NsL
xsB9/tauE0O+afIUFB9kpgIgSVp6RCEn5rSsQJb6Aq2TDhZmfde8bZKZ69frcZg1
kGQAdgBo9pj4H2SCvjqM7rkoHUz8cVFdZ5PURNEKZ6y7T0/7xAAAAUx2gFmTAAAE
AwBHMEUCIBEiosKJY9dxJooU/E7xhUNdhmGtCowHEylch+5S04pKAiEAttlf10XA
j7+tO8LYQs3v8dLFhbZt4FXvChY8InyAmtMAdgBWFAaaL9fC7NP14b1Esj7HRna5
vJkRXMDvlJhV1onQ3QAAAUx2gFrcAAAEAwBHMEUCIF9tTRcTdyhUT8dh9AO4YEsW
F7p0PZZ44h4iDuUBQqC3AiEApE3LND9uQOxHebpxic5XbrlNRojGZbHwOitjMfBQ
gwgwDQYJKoZIhvcNAQELBQADggEBAL1PRPqVj67sJHpPPx4heorseGqu/i5BMtLS
bDf6QKZKlWlBBdFjh56pjMlpTgeU65pkI13SWmEFtJfWazRTYWo3KMTv9Lg5kvqf
2U/ufStgcybN4H3JFJXpfO1q2t5TA35v3wt4TLT68NQJQQ6C2fNXNpfkaOCWjAui
SckpZ7MmKfi5WcDAxp3u6fppCz1R2ZeIGclD4cF7Q170dDfwIJMzrs+0j6EJwNGn
PxHydT3a0gswOOOXn2EaSqs8NiELzgd9WMwFacsqW36SbWk3rNtBMp9FUfjtaq8i
axIXj1Bn5LCy11cr8qXvzUrPdDeff11Eucf7up1RRW+1I5kxWgM=
-----END CERTIFICATE-----
subject=/businessCategory=Government Entity/jurisdictionC=US/serialNumber=Government Entity/street=6401 Security Blvd./postalCode=21235/C=US/ST=Maryland/L=Balitmore/O=Social Security Administration/CN=secure.ssa.gov
issuer=/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 Extended Validation Server CA
---
No client certificate CA names sent
---
SSL handshake has read 4254 bytes and written 633 bytes
---
New, TLSv1/SSLv3, Cipher is AES256-SHA
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1
    Cipher    : AES256-SHA
    Session-ID: 0000023FE037474E0E05B781697F099772307D3758585858577F69E50008BB07
    Session-ID-ctx: 
    Master-Key: 73BA9F24D8A9871187B56874B33FC2C131F0A3F77BA8F8C58A5D59DE72BA958DE0983473213ED07D71B02615A65CB0CC
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1467967973
    Timeout   : 300 (sec)
    Verify return code: 19 (self signed certificate in certificate chain)
---
```

**Comment by kinichiro** [comment] 2016-07-08 14:41
Hi,
I think this issue was fixed by commit https://github.com/libressl-portable/openbsd/commit/c69dd72aa32f7a51c866e935403d6b336c45ed18 , and distribution tar.gz is not released yet.
You can avoid this error by adding `-CAfile` option.

```
$ openssl version
LibreSSL 2.3.2
$ openssl s_client -connect secure.ssa.gov:443 -CAfile /usr/local/etc/ssl/cert.pem
...
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
```

Best regards,

**Comment by kinichiro** [comment] 2016-07-08 14:48
s_client ignores CA files in openssldir https://github.com/libressl-portable/openbsd/issues/62

**Comment by toddfries** [comment] 2016-07-08 16:37
$ openssl version
LibreSSL 2.4.2

**Comment by kinichiro** [comment] 2016-07-08 17:00
Do you have cert.pem in your OPENSSLDIR ?

```
$ ./openssl version -a
LibreSSL 2.4.2
built on: date not available
platform: information not available
options:  bn(64,64) rc4(16x,int) des(idx,cisc,16,int) idea(int) blowfish(idx)
compiler: information not available
OPENSSLDIR: "/usr/local/etc/ssl"
$
$ ls /usr/local/etc/ssl/cert.pem
/usr/local/etc/ssl/cert.pem
$
$ ./openssl s_client -connect secure.ssa.gov:443
CONNECTED(00000003)
...
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
```

**Comment by toddfries** [comment] 2016-07-08 20:02
$ openssl version -a
LibreSSL 2.4.2
built on: date not available
platform: information not available
options:  bn(64,64) rc4(16x,int) des(idx,cisc,16,int) idea(int) blowfish(idx) 
compiler: information not available
OPENSSLDIR: "/etc/ssl"
$ ls -l /etc/ssl/cert.pem
-r--r--r--  1 root  bin  189049 Jun  6 13:04 /etc/ssl/cert.pem

**Comment by toddfries** [comment] 2016-07-08 20:03
why does cert.pem have anything to do with the fact that the initially sent packet is never responded to with openssl (base OpenBSD) but with eopenssl (ports packaged bloatware openssl) it works?

**Comment by busterb** [comment] 2016-07-11 03:30
What OS is this? Are you running an OpenBSD 6.0 snapshot?

**Comment by busterb** [comment] 2016-07-11 03:43
I haven't managed to reproduce either on Ubuntu 16.04 running the latest 2.4.2 or the current OpenBSD snapshot.

**Comment by toddfries** [comment] 2016-07-11 15:05
Yes, OpenBSD/amd64 6.0 snapshot

OpenBSD 6.0-beta (GENERIC.MP) #2248: Sat Jul  2 21:59:30 MDT 2016
    deraadt@amd64.openbsd.org:/usr/src/sys/arch/amd64/compile/GENERIC.MP
real mem = 8477106176 (8084MB)
avail mem = 8215654400 (7835MB)
mpath0 at root
scsibus0 at mpath0: 256 targets
mainbus0 at root
bios0 at mainbus0: SMBIOS rev. 2.7 @ 0xe0840 (54 entries)
bios0: vendor LENOVO version "B9CN16WW" date 12/26/2014
bios0: LENOVO 80H1
acpi0 at bios0: rev 2
acpi0: sleep states S0 S1 S3 S4 S5
acpi0: tables DSDT FACP ASF! HPET LPIT APIC MCFG SSDT SSDT SSDT SSDT SSDT UEFI MSDM BATB FPDT SLIC UEFI CSRT
acpi0: wakeup devices P0P1(S4) GLAN(S4) EHC1(S3) EHC2(S3) XHC_(S3) HDEF(S4) TPD4(S4) TPD7(S0) TPD8(S0) PXSX(S4) RP01(S4) PXSX(S4) RP02(S4) PXSX(S4) RP03(S4) PXSX(S4) [...]
acpitimer0 at acpi0: 3579545 Hz, 24 bits
acpihpet0 at acpi0: 14318179 Hz
acpimadt0 at acpi0 addr 0xfee00000: PC-AT compat
cpu0 at mainbus0: apid 0 (boot processor)
cpu0: Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz, 1596.55 MHz
cpu0: FPU,VME,DE,PSE,TSC,MSR,PAE,MCE,CX8,APIC,SEP,MTRR,PGE,MCA,CMOV,PAT,PSE36,CFLUSH,DS,ACPI,MMX,FXSR,SSE,SSE2,SS,HTT,TM,PBE,SSE3,PCLMUL,DTES64,MWAIT,DS-CPL,VMX,EST,TM2,SSSE3,FMA3,CX16,xTPR,PDCM,PCID,SSE4.1,SSE4.2,MOVBE,POPCNT,DEADLINE,AES,XSAVE,AVX,F16C,RDRAND,NXE,PAGE1GB,LONG,LAHF,ABM,PERF,ITSC,FSGSBASE,BMI1,AVX2,SMEP,BMI2,ERMS,INVPCID,SENSOR,ARAT
cpu0: 256KB 64b/line 8-way L2 cache
cpu0: smt 0, core 0, package 0
mtrr: Pentium Pro MTRR support, 10 var ranges, 88 fixed ranges
cpu0: apic clock running at 99MHz
cpu0: mwait min=64, max=64, C-substates=0.2.1.2.4.1.1.1, IBE
cpu1 at mainbus0: apid 1 (application processor)
cpu1: Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz, 1596.30 MHz
cpu1: FPU,VME,DE,PSE,TSC,MSR,PAE,MCE,CX8,APIC,SEP,MTRR,PGE,MCA,CMOV,PAT,PSE36,CFLUSH,DS,ACPI,MMX,FXSR,SSE,SSE2,SS,HTT,TM,PBE,SSE3,PCLMUL,DTES64,MWAIT,DS-CPL,VMX,EST,TM2,SSSE3,FMA3,CX16,xTPR,PDCM,PCID,SSE4.1,SSE4.2,MOVBE,POPCNT,DEADLINE,AES,XSAVE,AVX,F16C,RDRAND,NXE,PAGE1GB,LONG,LAHF,ABM,PERF,ITSC,FSGSBASE,BMI1,AVX2,SMEP,BMI2,ERMS,INVPCID,SENSOR,ARAT
cpu1: 256KB 64b/line 8-way L2 cache
cpu1: smt 1, core 0, package 0
cpu2 at mainbus0: apid 2 (application processor)
cpu2: Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz, 1596.30 MHz
cpu2: FPU,VME,DE,PSE,TSC,MSR,PAE,MCE,CX8,APIC,SEP,MTRR,PGE,MCA,CMOV,PAT,PSE36,CFLUSH,DS,ACPI,MMX,FXSR,SSE,SSE2,SS,HTT,TM,PBE,SSE3,PCLMUL,DTES64,MWAIT,DS-CPL,VMX,EST,TM2,SSSE3,FMA3,CX16,xTPR,PDCM,PCID,SSE4.1,SSE4.2,MOVBE,POPCNT,DEADLINE,AES,XSAVE,AVX,F16C,RDRAND,NXE,PAGE1GB,LONG,LAHF,ABM,PERF,ITSC,FSGSBASE,BMI1,AVX2,SMEP,BMI2,ERMS,INVPCID,SENSOR,ARAT
cpu2: 256KB 64b/line 8-way L2 cache
cpu2: smt 0, core 1, package 0
cpu3 at mainbus0: apid 3 (application processor)
cpu3: Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz, 1596.30 MHz
cpu3: FPU,VME,DE,PSE,TSC,MSR,PAE,MCE,CX8,APIC,SEP,MTRR,PGE,MCA,CMOV,PAT,PSE36,CFLUSH,DS,ACPI,MMX,FXSR,SSE,SSE2,SS,HTT,TM,PBE,SSE3,PCLMUL,DTES64,MWAIT,DS-CPL,VMX,EST,TM2,SSSE3,FMA3,CX16,xTPR,PDCM,PCID,SSE4.1,SSE4.2,MOVBE,POPCNT,DEADLINE,AES,XSAVE,AVX,F16C,RDRAND,NXE,PAGE1GB,LONG,LAHF,ABM,PERF,ITSC,FSGSBASE,BMI1,AVX2,SMEP,BMI2,ERMS,INVPCID,SENSOR,ARAT
cpu3: 256KB 64b/line 8-way L2 cache
cpu3: smt 1, core 1, package 0
ioapic0 at mainbus0: apid 2 pa 0xfec00000, version 20, 40 pins
acpimcfg0 at acpi0 addr 0xf8000000, bus 0-63
acpiprt0 at acpi0: bus 0 (PCI0)
acpiprt1 at acpi0: bus -1 (P0P1)
acpiprt2 at acpi0: bus 1 (RP01)
acpiprt3 at acpi0: bus 2 (RP03)
acpiprt4 at acpi0: bus 3 (RP04)
acpiprt5 at acpi0: bus -1 (RP05)
acpiprt6 at acpi0: bus -1 (PEG0)
acpiprt7 at acpi0: bus -1 (PEG1)
acpiprt8 at acpi0: bus -1 (PEG2)
acpiec0 at acpi0
acpicpu0 at acpi0: C3(200@506 mwait.1@0x60), C2(200@148 mwait.1@0x33), C1(1000@1 mwait.1), PSS
acpicpu1 at acpi0: C3(200@506 mwait.1@0x60), C2(200@148 mwait.1@0x33), C1(1000@1 mwait.1), PSS
acpicpu2 at acpi0: C3(200@506 mwait.1@0x60), C2(200@148 mwait.1@0x33), C1(1000@1 mwait.1), PSS
acpicpu3 at acpi0: C3(200@506 mwait.1@0x60), C2(200@148 mwait.1@0x33), C1(1000@1 mwait.1), PSS
acpitz0 at acpi0: critical temperature is 95 degC
acpitz1 at acpi0: critical temperature is 126 degC
"INT3F0D" at acpi0 not configured
acpiac0 at acpi0: AC unit online
acpibat0 at acpi0: BAT0 model "L13M4P61" serial  1264 type LiP oem "313100504d53"
"VPC2004" at acpi0 not configured
"IDEA0102" at acpi0 not configured
"SYN2B3A" at acpi0 not configured
acpibtn0 at acpi0: LID0
acpibtn1 at acpi0: SLPB
"PNP0C14" at acpi0 not configured
"PNP0C14" at acpi0 not configured
"INT340E" at acpi0 not configured
acpivideo0 at acpi0: GFX0
acpivout0 at acpivideo0: DD1F
cpu0: Enhanced SpeedStep 1596 MHz: speeds: 2401, 2400, 2300, 2200, 2000, 1900, 1700, 1600, 1500, 1400, 1300, 1200, 1100, 900, 800, 768 MHz
pci0 at mainbus0 bus 0
pchb0 at pci0 dev 0 function 0 "Intel Core 4G Host" rev 0x0b
inteldrm0 at pci0 dev 2 function 0 "Intel HD Graphics" rev 0x0b
drm0 at inteldrm0
inteldrm0: msi
inteldrm0: 1920x1080
wsdisplay0 at inteldrm0 mux 1: console (std, vt100 emulation)
wsdisplay0: screen 1-5 added (std, vt100 emulation)
azalia0 at pci0 dev 3 function 0 "Intel Core 4G HD Audio" rev 0x0b: msi
xhci0 at pci0 dev 20 function 0 "Intel 8 Series xHCI" rev 0x04: msi
usb0 at xhci0: USB revision 3.0
uhub0 at usb0 "Intel xHCI root hub" rev 3.00/1.00 addr 1
"Intel 8 Series MEI" rev 0x04 at pci0 dev 22 function 0 not configured
azalia1 at pci0 dev 27 function 0 "Intel 8 Series HD Audio" rev 0x04: msi
azalia1: codecs: Realtek/0x0233
audio0 at azalia1
ppb0 at pci0 dev 28 function 0 "Intel 8 Series PCIE" rev 0xe4
pci1 at ppb0 bus 1
ppb1 at pci0 dev 28 function 2 "Intel 8 Series PCIE" rev 0xe4: msi
pci2 at ppb1 bus 2
iwm0 at pci2 dev 0 function 0 "Intel Dual Band Wireless AC 3160" rev 0x93, msi
ppb2 at pci0 dev 28 function 3 "Intel 8 Series PCIE" rev 0xe4: msi
pci3 at ppb2 bus 3
re0 at pci3 dev 0 function 0 "Realtek 8168" rev 0x10: RTL8168GU/8111GU (0x5080), msi, address 54:ee:75:33:28:56
rgephy0 at re0 phy 7: RTL8251 PHY, rev. 0
pcib0 at pci0 dev 31 function 0 "Intel 8 Series LPC" rev 0x04
ahci0 at pci0 dev 31 function 2 "Intel 8 Series AHCI" rev 0x04: msi, AHCI 1.3
ahci0: port 0: 6.0Gb/s
scsibus1 at ahci0: 32 targets
sd0 at scsibus1 targ 0 lun 0: <ATA, WDC WD10SPCX-24H, 02.0> SCSI3 0/direct fixed naa.50014ee6af9b039f
sd0: 953869MB, 512 bytes/sector, 1953525168 sectors
ichiic0 at pci0 dev 31 function 3 "Intel 8 Series SMBus" rev 0x04: apic 2 int 18
iic0 at ichiic0
spdmem0 at iic0 addr 0x50: 4GB DDR3 SDRAM PC3-12800 SO-DIMM
spdmem1 at iic0 addr 0x52: 4GB DDR3 SDRAM PC3-12800 SO-DIMM
isa0 at pcib0
isadma0 at isa0
pckbc0 at isa0 port 0x60/5 irq 1 irq 12
pckbd0 at pckbc0 (kbd slot)
wskbd0 at pckbd0: console keyboard, using wsdisplay0
pms0 at pckbc0 (aux slot)
wsmouse0 at pms0 mux 0
pms0: Synaptics clickpad, firmware 8.1
pcppi0 at isa0 port 0x61
spkr0 at pcppi0
error: [drm:pid0:intel_uncore_check_errors] *ERROR* Unclaimed register before interrupt
uhub1 at uhub0 port 2 "Silitek IBM USB HUB KEYBOARD" rev 1.10/0.01 addr 2
uhidev0 at uhub1 port 1 configuration 1 interface 0 "Silitek IBM USB HUB KEYBOARD" rev 1.10/0.01 addr 3
uhidev0: iclass 3/1
ukbd0 at uhidev0: 8 variable keys, 6 key codes
wskbd1 at ukbd0 mux 1
wskbd1: connecting to wsdisplay0
uhidev1 at uhub1 port 1 configuration 1 interface 1 "Silitek IBM USB HUB KEYBOARD" rev 1.10/0.01 addr 3
uhidev1: iclass 3/0, 3 report ids
uhid0 at uhidev1 reportid 1: input=1, output=0, feature=0
uhid1 at uhidev1 reportid 2: input=1, output=0, feature=0
uhid2 at uhidev1 reportid 3: input=3, output=1, feature=0
uvideo0 at uhub0 port 4 configuration 1 interface 0 "Generic Lenovo EasyCamera" rev 2.00/36.02 addr 4
video0 at uvideo0
uhub2 at uhub0 port 5 "Terminus Technology USB 2.0 Hub [MTT]" rev 2.00/1.00 addr 5
umass0 at uhub2 port 5 configuration 1 interface 0 "MediaTek Inc MT1807" rev 2.00/0.00 addr 6
umass0: using ATAPI over Bulk-Only
scsibus2 at umass0: 2 targets, initiator 0
cd0 at scsibus2 targ 1 lun 0: <HL-DT-ST, DVDRAM GP40NB40, 1.00> ATAPI 5/cdrom removable serial.0e8d1807546_
uhidev2 at uhub2 port 6 configuration 1 interface 0 "HID-compliant Mouse HID-compliant Mouse" rev 1.10/1.00 addr 7
uhidev2: iclass 3/1
ums0 at uhidev2: 5 buttons, Z dir
wsmouse1 at ums0 mux 0
uhub3 at uhub2 port 7 "Terminus Technology USB 2.0 Hub [MTT]" rev 2.00/1.00 addr 8
umodem0 at uhub3 port 2 configuration 1 interface 0 "Alcor Micro product 0x9720" rev 1.10/0.00 addr 9
umodem0: data interface 1, has no CM over data, has break
umodem0: status change notification available
ucom0 at umodem0
umass1 at uhub3 port 4 configuration 1 interface 0 "Android Android" rev 2.00/2.31 addr 10
umass1: using SCSI over Bulk-Only
scsibus3 at umass1: 2 targets, initiator 0
sd1 at scsibus3 targ 1 lun 0: <Linux, File-CD Gadget, 0000> SCSI2 0/direct removable
sd2 at scsibus3 targ 1 lun 1: <Linux, File-CD Gadget, 0000> SCSI2 0/direct removable
cd1 at scsibus3 targ 1 lun 2: <Linux, File-CD Gadget, 0000> SCSI2 5/cdrom removable
ugen0 at uhub3 port 4 configuration 1 "Android Android" rev 2.00/2.31 addr 10
ugen1 at uhub0 port 6 "Intel product 0x07dc" rev 2.00/0.01 addr 11
uhidev3 at uhub0 port 8 configuration 1 interface 0 "Atmel Atmel maXTouch Digitizer" rev 2.00/10.99 addr 12
uhidev3: iclass 3/0, 5 report ids
ums1 at uhidev3 reportid 1: 1 button, tip
wsmouse2 at ums1 mux 0
uhid3 at uhidev3 reportid 2: input=0, output=0, feature=1
ums2 at uhidev3 reportid 5
ums2: mouse has no X report
uhidev4 at uhub0 port 8 configuration 1 interface 1 "Atmel Atmel maXTouch Digitizer" rev 2.00/10.99 addr 12
uhidev4: iclass 3/0, 2 report ids
uhid4 at uhidev4 reportid 1: input=63, output=63, feature=0
uhid5 at uhidev4 reportid 2: input=63, output=63, feature=0
vscsi0 at root
scsibus4 at vscsi0: 256 targets
softraid0 at root
scsibus5 at softraid0: 256 targets
sd3 at scsibus5 targ 1 lun 0: <OPENBSD, SR CRYPTO, 006> SCSI2 0/direct fixed
sd3: 953866MB, 512 bytes/sector, 1953519473 sectors
root on sd3a (ecb0250e86a1b240.a) swap on sd3b dump on sd3b
iwm0: hw rev 0x160, fw ver 16.242414.0, address d0:7e:35:12:9a:03

**Comment by bob-beck** [comment] 2016-07-14 02:47
I can not reproduce, at least with a July 7 snapshot

**Comment by bob-beck** [comment] 2016-07-14 02:49
Unable to reproduce - We can reopen if we are able to determine this is real.

**Closed by bob-beck** 2016-07-14 02:49 UTC
